### ISSUE TITLE
SQLite database is locked

### ISSUE THREAD

**Issue by nikrou** [nikrou/phyxo#38]
After installation, there's a php exception : SQLite database is locked.

**Comment by nikrou** [comment]
Since SQLite does not support row level locks but locks the whole
database, it's better to use native session saved to files.
Create or append to **config/services_prod.yaml** file following lines :

```yaml
framework:
  session:
    handler_id: session.handler.native_file
```
